name: ticketing-api

services:
  app:
    build:
      context: .
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    env_file:
      - .env
    restart: always
    networks:
      - ticketing-network
    depends_on:
      - db

  db:
    image: postgres:latest
    env_file:
      - .env
    restart: always
    volumes:
      - ticketing_db_folder:/var/lib/postgresql/data
    networks:
      - ticketing-network

volumes:
  ticketing_db_folder:

networks:
  ticketing-network: